### ISSUE TITLE
How to prepare the dataset

### ISSUE THREAD

**Issue by Cassie-CV** [CityU-AIM-Group/DSI-Net#1]
Hi, thanks for share the code, how to prepare the dataset,e.g., the image_list ('data/WCE/WCE_Dataset_image_list.pkl'), and the data (DATA_ROOT = '/home/meiluzhu2/data/WCE/WCE_larger') ?

**Comment by meiluzhu** [comment]
> Hi, thanks for share the code, how to prepare the dataset,e.g., the image_list ('data/WCE/WCE_Dataset_image_list.pkl'), and the data (DATA_ROOT = '/home/meiluzhu2/data/WCE/WCE_larger') ?

**Comment by meiluzhu** [comment]
> Hi, thanks for share the code, how to prepare the dataset,e.g., the image_list ('data/WCE/WCE_Dataset_image_list.pkl'), and the data (DATA_ROOT = '/home/meiluzhu2/data/WCE/WCE_larger') ?

Thanks for your interests into our work.  The code about the preparation of dataset has been uploaded. Please check it under 'dataset'.

**Comment by Cassie-CV** [comment]
> > Hi, thanks for share the code, how to prepare the dataset,e.g., the image_list ('data/WCE/WCE_Dataset_image_list.pkl'), and the data (DATA_ROOT = '/home/meiluzhu2/data/WCE/WCE_larger') ?
> 
> Thanks for your interests into our work. The code about the preparation of dataset has been uploaded. Please check it under 'dataset'.

Thank you very much！
