### ISSUE TITLE
how to download the two dataset？

### ISSUE THREAD

**Issue by xuxingyuan98** [CityU-AIM-Group/DSI-Net#2]
前辈您好，我阅读了您的论文大受启发，想复现一下论文中的实验。由于我搜集信息的能力欠佳，没能从互联网上下载到文中的两个数据集，如能回复万分感谢。

**Comment by KarryRen** [comment]
Thank you for making the code open source, but I'm having the same problem as the friend above, failing to search for a way to download the two open source datasets, can you point me in the right direction if you can?
