### ISSUE TITLE
How to Find the Two Datasets ?

### ISSUE THREAD

**Issue by KarryRen** [CityU-AIM-Group/DSI-Net#4]
Thank you for making the code open source, but I'm having the same problem as the friend above, failing to search for a way to download the two open source datasets, can you point me in the right direction if you can?

**Comment by meiluzhu** [comment]
Sorry for late reply. You can find the processed dataset via https://drive.google.com/file/d/1BBF21SVlH5685XpsvtKlWN7iepr7YQPU/view?usp=sharing
