### ISSUE TITLE
dataset/my_datasets.py里面发现了一行错误

### ISSUE THREAD

**Issue by tinicc77** [CityU-AIM-Group/DSI-Net#5]
![c5e52a215ff84445a87d73607747786](https://github.com/user-attachments/assets/7b257f97-a437-4e31-b8ec-f8bfff2b47ea)
aassert用法这里没出错吗？

**Comment by meiluzhu** [comment]
Hi, 采用(data_type = 'train' and mode = 'train')或者(data_type = 'train' and mode = 'test' )或者(data_type = 'test' and mode = 'test')这三种设置中的其中一种。我这边是并没有报错的。你可以展示一下具体错误。

**Comment by tinicc77** [comment]
OK,谢谢！有其他问题再向您咨询。当时不知道为什么跑完报错了，后面第二次尝试就好了。感谢回复，祝您科研顺利！
